services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=medidor
    volumes:
      - polls_pg_data:/bitnami/postgresql
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  polls_pg_data:

networks:
  app-network:
    driver: bridge
