services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=medidor
    volumes:
      - reading_data:/bitnami/postgresql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - c:\dados-docker\volumes\images:/app/temp
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  reading_data:
  temp:

networks:
  app-network:
    driver: bridge
